### ISSUE TITLE
吴范发动预言获得奋音报错

### ISSUE THREAD

**Issue by XiaCizhaogedade** [Tipx-L/decade-ui#11]
不知道是不是我自己的问题？是我设置错了还是要重新现在游戏？
![Screenshot_20231007_162329_yuri nakamura noname_android](https://github.com/Tipx-L/decade-ui/assets/147239458/9464487f-bcfd-4a1a-9b30-171ca3ee2c69)
![Screenshot_20231007_162340_yuri nakamura noname_android](https://github.com/Tipx-L/decade-ui/assets/147239458/85b2a3fb-8106-4c74-8537-58b7d7d80a71)
![Screenshot_20231007_162353_yuri nakamura noname_android](https://github.com/Tipx-L/decade-ui/assets/147239458/7c67c436-de38-4432-8a8f-e12cfb311081)
![Screenshot_20231007_162357_yuri nakamura noname_android](https://github.com/Tipx-L/decade-ui/assets/147239458/b9af058c-080c-4be5-b27d-54f7fdf2676c)
![Screenshot_20231007_162402_yuri nakamura noname_android](https://github.com/Tipx-L/decade-ui/assets/147239458/b62ea09a-6b4b-4995-ba81-47dcf95907b6)

**Comment by Tipx-L** [comment]
在濒死事件触发的，应该不是〖预言〗的问题（至少我没测试出来）。
你看看其他角色能不能出现这问题。

**Comment by XiaCizhaogedade** [comment]
又试了一边只有吴范这样 别的武将不会出现这个问题  你的你的不会卡死吗？
我用不用卸载了重新装一遍无名杀？
错误文件: extension/十周年UI/extension.js
错误信息: Uncaught TypeError: Cannot read property 'enable' of undefined
错误提示: 无法读取'undefined'的属性值'enable'
行号: 4488
列号: 26
无名杀版本: 1.10.3.1
event.name: chooseToUse
event.step: 0
event.parent.name: _save
event.parent.step: 2
event.parent.parent.name: dying
event.parent.parent.step: 2
-------------
player: 吴范[wufan]
座位号: 3
-------------
4484| 								game.expandSkills(skills2);
4485| 								for (i = 0; i < skills2.length; i++) {
4486| 									info = get.info(skills2[i]);
4487| 									enable = false;
4488| ⚠️									if (typeof info.enable == 'function') enable = info.enable(event);
4489| 									else if (typeof info.enable == 'object') enable = info.enable.contains(event.name);
4490| 									else if (info.enable == 'phaseUse') enable = (event.type == 'phase');
4491| 									else if (typeof info.enable == 'string') enable = (info.enable == event.name);
4492| 
4493| 									if (enable) {
4494| 										if (!game.expandSkills(player.getSkills(false).concat(lib.skill.global)).contains(skills2[i]) && (info.noHidden || get.mode() != 'guozhan' || player.hasSkillTag('nomingzhi', false, null, true))) enable = false;

-------------
TypeError: Cannot read property 'enable' of undefined
    at Object.game.check (extension/十周年UI/extension.js:4488:26)
    at Object.eval [as content] (eval at Legacy (game/game.js:11105:14), <anonymous>:62:23)
    at Object.tryContent (extension/十周年UI/extension.js:9008:13)
    at Object.loop (extension/十周年UI/extension.js:8961:23)
    at Object.loop (extension/十周年UI/extension.js:4099:30)
    at resume (game/game.js:38789:10)

**Comment by Tipx-L** [comment]
你检查一下是否因为一些原因（如隐藏了武将包）导致DIY武将包不存在
`iwasawa_refenyin`这个技能需要保证DIY包存在才能获得

**Comment by XiaCizhaogedade** [comment]
确实恢复了DIY武将包就好了 谢谢
