### ISSUE TITLE
[无名杀PR版本适配问题]

### ISSUE THREAD

**Issue by universe-st** [Tipx-L/decade-ui#12]
1、将player、card等抽出为类后，Mixin.redirct发生问题，无法正确的修改类成员函数。建议加上逻辑判断。

2、本体重写了phase流程，十周年UI中修改的phase需要跟进。

3、对ui.create.player、ui.create.card两个方法的修改行为需要进行以下替代：
改为修改lib.element.player.build 和 lib.element.player.card.build
逻辑修改：①去掉第一个parent参数。②首句加声明let player/card = this; ③去除原来的复制lib.element.player/card中函数的操作。

**Comment by Tipx-L** [comment]
新版本已发布。
81801f6
