### ISSUE TITLE
刘晔霹雳车的图片有问题

### ISSUE THREAD

**Issue by wxsthuee** [Tipx-L/decade-ui#3]
改版刘晔霹雳车是宝物，而且没有攻击范围
大佬能做一个宝物霹雳车的图片嘛

**Comment by Tipx-L** [comment]
图片不是我做的，我得找人问问
另外能提供一下相关截图吗

**Comment by wxsthuee** [comment]
> 图片不是我做的，我得找人问问 另外能提供一下相关截图吗

这个：
<img width="390" alt="image" src="https://github.com/Tipx-L/decade-ui/assets/6491355/f29c8902-ed9d-4737-b1eb-a70aecede65c">

**Comment by Tipx-L** [comment]
![image](https://github.com/Tipx-L/decade-ui/assets/138244655/6a465b29-a26b-48e9-9ccc-3defd0ae2a8e)
![image](https://github.com/Tipx-L/decade-ui/assets/138244655/e6ff238e-2192-4039-aa38-a42592b52520)
959d6b1
