### ISSUE TITLE
谋刘备限定技章武报错

### ISSUE THREAD

**Issue by SmeraldoTAT** [Tipx-L/decade-ui#4]
如题

**Comment by Tipx-L** [comment]
具体是报了什么错，能否截图？

**Comment by SmeraldoTAT** [comment]
![ab3cdbd7cdf3dbbd1e0f0f4d50152b05](https://github.com/Tipx-L/decade-ui/assets/145491587/3e881a0a-d70a-4739-b618-24eee012488a)
![9ee334929cbab3fb78ec422f7b10776b](https://github.com/Tipx-L/decade-ui/assets/145491587/caebade0-09ab-4136-ba9e-fe27a9b85a0f)

**Comment by Tipx-L** [comment]
已修复。
