### ISSUE TITLE
神典韦一技能挈挟报错

### ISSUE THREAD

**Issue by wubocheng612** [Tipx-L/decade-ui#5]
![Screenshot_2023-09-30-05-34-45-269_com noname shijian](https://github.com/Tipx-L/decade-ui/assets/146490773/e536a5cf-8ce3-46b7-8808-d1ad1c602b0a)
![Screenshot_2023-09-30-05-34-00-022_bin mt plus](https://github.com/Tipx-L/decade-ui/assets/146490773/7abfdfe6-d565-41cf-87bd-2a3377e70e16)

**Comment by Tipx-L** [comment]
已修复。
