### ISSUE TITLE
普通杀有概率转换为属性杀

### ISSUE THREAD

**Issue by cheersni** [Tipx-L/decade-ui#7]
最新版本体（1.10.3.1，1.10.2.1也有），使用黑色普通杀时，有概率转换为雷杀，使用红色普通杀时，有概率转换为火杀

**Comment by Tipx-L** [comment]
请问一般会在什么时候“概率转换”？
或者也许新版本发布之后就顺便修复了。

**Comment by cheersni** [comment]
> 请问一般会在什么时候“概率转换”？ 或者也许新版本发布之后就顺便修复了。

就正常出杀就能出现，用张飞，给他多摸几张牌，多出几张杀，就能出现了，而且，谋刘备，回合内要用杀的时候，你会发现“仁德”展示的杀都是无属性的，正常应该是一张普通杀，一张雷杀和一张火杀的呀

**Comment by cheersni** [comment]
> 请问一般会在什么时候“概率转换”？ 或者也许新版本发布之后就顺便修复了。

我发现问题所在了，把卡牌美化关掉就行了。并不是普通杀被转化为属性杀了，而是属性杀没有被卡牌美化。雷杀火杀都显示为普通杀了

**Comment by Tipx-L** [comment]
哦，那这个问题应该在 b6abe72 修复了。
