### ISSUE TITLE
建议重构对本体gain事件的覆盖

### ISSUE THREAD

**Issue by universe-st** [Tipx-L/decade-ui#9]
《十周年UI》中对本体gain事件的覆盖的内容中，存在一些本体里声明了，但是十周年UI里没有声明的函数、变量。例如addv、frag1、frag2等，应该并非有意为之，而是错误，只不过因为没有触发一直被掩盖。
建议：
1、如没有必要，可取消覆盖gain事件。
2、如果有必须覆盖实现的效果，弄清楚未声明变量的用途，并添加声明。可以在本体最新的gain事件的基础上重写。

**Comment by Tipx-L** [comment]
现在`lib.element.content.gain`采用了全新的注入方式，因此不再需要覆盖了。
